-- PostgreSQL 业务幂等表。
-- 本文件可以重复执行：表和索引均使用 IF NOT EXISTS。
-- LangGraph PostgresSaver 会创建自己的 checkpoint 表，不要与这两张表混用。

CREATE TABLE IF NOT EXISTS agent_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    thread_id VARCHAR(128) NOT NULL,
    message_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    response JSONB NULL,
    error_message TEXT NULL,
    execution_token VARCHAR(64) NOT NULL,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agent_request_owner_request UNIQUE (owner_id, request_id),
    CONSTRAINT chk_agent_request_status
        CHECK (status IN ('running', 'completed', 'confirmation_required', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_agent_request_thread
    ON agent_request (owner_id, thread_id, create_time DESC);

CREATE TABLE IF NOT EXISTS tool_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    thread_id VARCHAR(128) NOT NULL,
    call_id VARCHAR(128) NOT NULL,
    tool_name VARCHAR(100) NOT NULL,
    status VARCHAR(16) NOT NULL,
    arguments JSONB NOT NULL,
    result JSONB NULL,
    error_message TEXT NULL,
    latency_ms INTEGER NULL,
    execution_token VARCHAR(64) NOT NULL,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tool_execution_owner_call UNIQUE (owner_id, call_id),
    CONSTRAINT chk_tool_execution_status
        CHECK (status IN ('running', 'success', 'failed')),
    CONSTRAINT chk_tool_execution_latency
        CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_tool_execution_request
    ON tool_execution (owner_id, request_id, create_time DESC);

CREATE INDEX IF NOT EXISTS idx_tool_execution_thread
    ON tool_execution (owner_id, thread_id, create_time DESC);

CREATE INDEX IF NOT EXISTS idx_tool_execution_tool_status
    ON tool_execution (tool_name, status);

COMMENT ON TABLE agent_request IS 'Agent HTTP 请求级幂等与恢复状态';
COMMENT ON TABLE tool_execution IS 'Agent Tool 调用级幂等、租约与 fencing token';
