-- Agent 三层记忆的业务表。
--
-- 这些表服务于消息查询、滚动摘要和长期事实检索。LangGraph Checkpointer 的
-- checkpoint/checkpoint_writes 等内部表由 PostgresSaver 管理，禁止在这里修改。

CREATE TABLE IF NOT EXISTS conversation_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    conversation_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_conversation_message_owner_message
        UNIQUE (owner_id, message_id),
    CONSTRAINT uq_conversation_message_owner_request_role
        UNIQUE (owner_id, request_id, role),
    CONSTRAINT chk_conversation_message_role
        CHECK (role IN ('user', 'assistant', 'tool')),
    CONSTRAINT chk_conversation_message_token_count
        CHECK (token_count >= 0),
    CONSTRAINT chk_conversation_message_content_length
        CHECK (char_length(content) BETWEEN 1 AND 20000)
);

CREATE INDEX IF NOT EXISTS idx_conversation_message_recent
    ON conversation_message (owner_id, conversation_id, create_time DESC, id DESC);

CREATE TABLE IF NOT EXISTS conversation_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL,
    conversation_id VARCHAR(128) NOT NULL,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    covered_until_message_id VARCHAR(64) NULL,
    version INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_conversation_summary_owner_conversation
        UNIQUE (owner_id, conversation_id),
    CONSTRAINT chk_conversation_summary_version CHECK (version >= 0)
);

CREATE TABLE IF NOT EXISTS memory_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    person_id VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL,
    value JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL,
    evidence_message_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence NUMERIC(5,4) NULL,
    requires_confirmation BOOLEAN NOT NULL DEFAULT TRUE,
    supersedes_fact_id VARCHAR(64) NULL,
    valid_from TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMPTZ(6) NULL,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_memory_fact_owner_fact UNIQUE (owner_id, fact_id),
    CONSTRAINT uq_memory_fact_owner_person_category_version
        UNIQUE (owner_id, person_id, category, version),
    CONSTRAINT chk_memory_fact_status
        CHECK (status IN ('active', 'pending_confirmation', 'superseded', 'rejected')),
    CONSTRAINT chk_memory_fact_version CHECK (version > 0),
    CONSTRAINT chk_memory_fact_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT chk_memory_fact_validity
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS idx_memory_fact_active_person
    ON memory_fact (owner_id, person_id, category, version DESC)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_memory_fact_pending
    ON memory_fact (owner_id, status, create_time DESC)
    WHERE status = 'pending_confirmation';

COMMENT ON TABLE conversation_message IS
    '可审计的原始会话消息；保存量与每次发送给模型的上下文量相互独立';
COMMENT ON TABLE conversation_summary IS
    '按 owner/conversation 保存的滚动结构化摘要及覆盖游标';
COMMENT ON TABLE memory_fact IS
    '带证据、版本和确认状态的长期业务事实；不保存未经校验的模型自由文本结论';
