-- 三层记忆的持久化任务表。
--
-- Agent 主链只负责保存原始消息并登记任务。摘要模型调用、事实版本写入由后台
-- 工作者完成；即使维护失败，也不会重新执行已经成功的 Neo4j Tool。

CREATE TABLE IF NOT EXISTS memory_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    conversation_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    job_type VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    available_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    execution_token VARCHAR(64) NULL,
    last_error TEXT NULL,
    create_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_memory_job_owner_job UNIQUE (owner_id, job_id),
    CONSTRAINT chk_memory_job_type
        CHECK (job_type IN ('summary', 'persist_facts')),
    CONSTRAINT chk_memory_job_status
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed')),
    CONSTRAINT chk_memory_job_attempts
        CHECK (attempts >= 0 AND max_attempts BETWEEN 1 AND 20)
);

CREATE INDEX IF NOT EXISTS idx_memory_job_claim
    ON memory_job (status, available_at, id)
    WHERE status IN ('pending', 'running', 'failed');

COMMENT ON TABLE memory_job IS
    '摘要和长期事实的可靠后台任务；任务失败不回滚或重跑业务 Tool';
